name: 'football_dbt'
version: '1.0.0'

profile: 'football_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  football_dbt:
    staging:
      +materialized: table
      +schema: staging
    gold:
      +materialized: table
      +schema: gold