football_dbt:
  outputs:
    production:
      type:   postgres
      host:   "{{ env_var('PGHOST') }}"
      dbname: "{{ env_var('PGDATABASE') }}"
      user:   "{{ env_var('PGUSER') }}"
      pass:   "{{ env_var('PGPASSWORD') }}"
      port:   5432
      schema: football_etl
  target: production